---

- name: Initialize Kubernetes
  shell: kubeadm init --apiserver-advertise-address={{ master_cidr }} --pod-network-cidr={{ pod_cidr }}


- name: Copy Kube admin config to root
  shell: |
    mkdir .kube
    cp /etc/kubernetes/admin.conf /root/.kube/config

- name: Copy Kube admin config
  shell: |
    mkdir /home/{{ user }}/.kube
    cp /etc/kubernetes/admin.conf /home/{{ user }}/.kube/config
    chown -R {{ user }}:{{ user }} /home/{{ user }}/.kube

- name: Copy Kube admin config to {{ user }}
  shell: |
    mkdir /{{ user }}/.kube
    cp /etc/kubernetes/admin.conf /{{ user }}/.kube/config


# - name: Deploy flannel network
#   shell: kubectl apply -f /vagrant/src/yaml/kube-flannel.yml

- name: Deploy calico network
  shell: kubectl --kubeconfig=/etc/kubernetes/admin.conf create -f https://docs.projectcalico.org/v3.16/manifests/calico.yaml >/dev/null 2>&1

- name: Generate Cluster join command
  shell: kubeadm token create --print-join-command > /tmp/joincluster.sh

- name: Copy to Ansible node joincluster.sh from master
  fetch:
    src: /tmp/joincluster.sh
    dest: /tmp/
    flat: yes
