---
# tasks file for kubernetes-components

# - name: Initialize Kubernetes Dashboard
#   shell: kubectl create -f /vagrant/src/yaml/dasshboard_v2.0.0-rc7.yaml

# - name: Initialize ARGO CD
#   shell: |
#     kubectl create namespace argocd
#     kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

- name: Initialize HELM
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

- name: Set up MetalLB Load Balancing for Bare Metal Kubernetes
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.5/manifests/namespace.yaml
    kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.5/manifests/metallb.yaml
    kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
    cat <<EOF | kubectl create -f -
    apiVersion: v1
    kind: ConfigMap
    metadata:
      namespace: metallb-system
      name: config
    data:
      config: |
        address-pools:
        - name: default
          protocol: layer2
          addresses:
          - 172.42.42.100-172.42.42.110
    EOF

- name: Allow pods use the master node
  shell: |
    kubectl taint node kmaster.example.com node-role.kubernetes.io/master:NoSchedule-
 
 - name:  Deploy and use Nginx ingress controller
  shell: |
    helm repo add stable https://charts.helm.sh/stable
    helm install test-nginx-ingress stable/nginx-ingress --set rbac.create=true
